### ISSUE TITLE
missing train.x train.y valid.x valid.y 

### ISSUE THREAD

**Issue by Lorenzoncina** [benob/recasepunc#21]
After having runned stage 2:
python recasepunc.py tensorize input.case+punc input.case+punc.x input.case+punc.y --lang $LANG

I can't run stage 3 cause I didn't get train.x train.y valid.x valid.y
python recasepunc.py train train.x train.y valid.x valid.y checkpoint/path --lang $LANG

How can I get this files?

**Comment by benob** [comment]
You have to create a train/valid/test Split and run the command on each of the subset.
