### ISSUE TITLE
Can't get attribute 'WordpieceTokenizer'

### ISSUE THREAD

**Issue by padmalcom** [benob/recasepunc#4]
Hi thanks for your effort on developing _recasepunc_! I know that you can't provide help for models not trained by you, but maybe you have an idea what's going wrong here:

I'm loading the model _vosk-recasepunc-de-0.21_ from [https://alphacephei.com/vosk/models](https://alphacephei.com/vosk/models). When I do so, torch tells me that it can't find _WordpieceTokenizer_. Do you know why? Is the model incompatible?

  Punc predict path: C:\Users\admin\meety\vosk-recasepunc-de-0.21\checkpoint
  Traceback (most recent call last):
    File "main2.py", line 120, in <module>
      t = transcriber()
    File "main2.py", line 32, in __init__
      self.casePuncPredictor = CasePuncPredictor(punc_predict_path, lang="de")
    File "C:\Users\admin\meety\recasepunc.py", line 273, in __init__
      loaded = torch.load(checkpoint_path, map_location=device if torch.cuda.is_available() else 'cpu')
    File "C:\Users\admin\Anaconda3\envs\meety\lib\site-packages\torch\serialization.py", line 607, in load
      return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    File "C:\Users\admin\Anaconda3\envs\meety\lib\site-packages\torch\serialization.py", line 882, in _load
      result = unpickler.load()
    File "C:\Users\admin\Anaconda3\envs\meety\lib\site-packages\torch\serialization.py", line 875, in find_class
      return super().find_class(mod_name, name)
  AttributeError: Can't get attribute 'WordpieceTokenizer' on <module '__main__' from 'main2.py'>

**Comment by marlon-br** [comment]
Hello, I was facing the same issue. There are two ways do address it:

1. Just `import WordpieceTokenizer` in you main script

2. Custom pickler:
```
import pickle

class Custompickler():
    class Unpickler(pickle.Unpickler):
        def find_class(self, module, name):
            if name == 'WordpieceTokenizer':
                return WordpieceTokenizer
            return super().find_class(module, name)
```

and set this pickler to `torch.load`

```
class CasePuncPredictor:
    def __init__(self, checkpoint_path, lang=default_config.lang, flavor=default_config.flavor,
                 device=default_config.device):
        loaded = torch.load(checkpoint_path, map_location='cpu', pickle_module=Custompickler)
```

**Comment by padmalcom** [comment]
Hi @marlon-br, I can not import WordpieceTokenizer (where from?) but including the custom pickler worked well!

**Comment by marlon-br** [comment]
WordpieceTokenizer is a part of transformers (https://huggingface.co/docs/transformers)

**Comment by padmalcom** [comment]
Thank you!
