### ISSUE TITLE
Can't do inference 

### ISSUE THREAD

**Issue by MatFrancois** [benob/recasepunc#7]
Hello,
I'm trying to use example.py on a french model (fr.22000 or fr-txt.large.19000)
But I have this error:
`    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
        Unexpected key(s) in state_dict: "bert.position_ids". `
I also tried with the following command, same error in output.
`python recasepunc.py predict fr.22000 < toto.txt > output.txt `
Do you have any advice? 
Thanks

**Comment by Enescigdem** [comment]
Hello , 
I have the same issue with French model

**Comment by benob** [comment]
It is likely a version mismatch of the transformers module. Are you using transformers==4.10.0?

**Comment by MatFrancois** [comment]
Indeed it works better like that. Thank you
